### PR TITLE
update to CKEditor 4.5.6

### PR DESCRIPTION
**Pull request by Marc-pi**

### CODE REVIEW

**Comment by voltan** [comment]
Please use old config file `www/script/editor/ckeditor/config.js`

**Comment by Marc-pi** [comment]
hum, there was no mention in changelog you modified this, i'll add it back
next time please update the changelog

**Comment by Marc-pi** [comment]
i allowed theme div classes. i don't think it is a showstopper (security wise), but this will help with the Page module when we need to build nice page layouts.

**Comment by voltan** [comment]
It have full support bootstrap ? we need find way to support `<i>` tag and full support class on `<ul>` , `<li>`, `` `<a>` , '<span>' , '<table>' tags

**Comment by Marc-pi** [comment]
Yes, i'll add this also when adding slope maps, there is a param just above, good shot

**Pull request merged**
