### PR TITLE
Update editor

### PR DESCRIPTION
**Pull request by voltan**
I had some feedback from customers about pi editor, they sad editor size is to small  and whit low options , need improvement

### CODE REVIEW

**Comment by Marc-pi** [comment]
@voltan hum, all those plugins are all usefull? 
it will be a nightmare to have such a long list... keep it simple is better imho
* please update the changelog
* you removed some usefull plugins

**Comment by voltan** [comment]
can you please tell me which plugin removed ?  I can add all of them again

**Comment by Marc-pi** [comment]
see the changelog :-)

**Comment by voltan** [comment]
I add embed plugins , but not add image2 , it remove main image plugin and than pelugin  needed for support extra upload systems like fileman

**Pull request merged**
