### PR TITLE
fix jquery 3 migration impacts (recatpcha, datepicker)

### PR DESCRIPTION
**Pull request by Marc-pi**

### CODE REVIEW

**Comment by voltan** [comment]
I think you need recheck this pull request and send it again

**Comment by Marc-pi** [comment]
@voltan ???? can you tell more about what you find? i did not send yet our latest changes, those are on my repo

**Comment by voltan** [comment]
I see just merge button not active some small fix needed I think . ( or perhaps sole on your repo )

**Comment by voltan** [comment]
Some notes : 
1- please use piengine.org domain on copyright texts
2- use  "php": ">=5.6.0",  https://github.com/pi-engine/pi/pull/1569/files#diff-b5d0ee8c97c7abd7e3fa29b9a27d1780L24
3- please fix  Conflicts https://github.com/pi-engine/pi/pull/1569/conflicts

**Comment by Marc-pi** [comment]
strange, seems i forgot to merge my previous send
i've fixed the conflicts
about code formatting, keep it for later

**Comment by voltan** [comment]
> about code formatting, keep it for later

It ok, it not have any effect, but I keep it for 2018 , ( just perhaps do it on some changes )

**Pull request merged**
