### PR TITLE
Login/Register in a Modal : end of work

### PR DESCRIPTION
**Pull request by Marc-pi**

### CODE REVIEW

**Comment by voltan** [comment]
Thanks for this changes 
Just if user module not installed ( for example on fresh install ) this part work? or we have blank page? this block loaded on first installation

**Comment by Marc-pi** [comment]
should, let us know if it does not work

**Comment by esprit-dev** [comment]
With my last work, system is not dependant from user module https://github.com/pi-engine/guide/issues/650

**Comment by voltan** [comment]
thank you very much

**Pull request merged**
