### PR TITLE
Work on pi

### PR DESCRIPTION
**Pull request by voltan**

### CODE REVIEW

**Comment by voltan** [comment]
Please check if it ok by your changes merge it @Marc-pi

**Comment by Marc-pi** [comment]
what do you advise me to test/check?
i need @sta2m to check if it does have impact on your code

**Comment by voltan** [comment]
I see last version of my changes have conflict by tour change, just if working on core now, please marge this change after your works merge , if no we can merge it

**Comment by Marc-pi** [comment]
you have to fix your conflicts and update your fork before commiting from your fork, to debug
i pushed my code before yours !

**Comment by voltan** [comment]
I refork pi repo this morning , but after merge your changes please merge this too

**Pull request merged**
